### ISSUE TITLE
Unable to fetch aan individual Gravity Form by its ID

### ISSUE THREAD

**Issue by chrismathews83** [harness-software/wp-graphql-gravity-forms#1]
Hi,

Unable to fetch an individual Gravity Form by its ID. How to get A valid global ID. Please let me know.

Thankyou

Query

``{
  gravityFormsForm(id:"1"){
    title
  }
}``

Result

`{
  "errors": [
    {
      "message": "A valid global ID must be provided.",
      "category": "user",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "gravityFormsForm"
      ]
    }
  ],
  "data": {
    "gravityFormsForm": null
  }
`}``

**Comment by kellenmace** [comment]
Hey Chris! Thanks for your interest in this plugin. 🙌🏼

In order to query for a form, you need to provide the `gravityFormsForm` query with a [Relay global ID](https://medium.com/code-oil/relay-graphql-de-mystifying-node-id-38757121b9c), rather than the ID of the Gravity Form.

You can create a Relay global ID like this:
`const id = btoa('GravityFormsForm:123')`
...where `123` is the ID of the Gravity Form you want to get. Then, you can pass that `id` to your query as a query variable.

`btoa()` is a JS function that converts the original string to a base-64 encoded string.

This is done for caching purposes. Like if your frontend JS app uses a client like Apollo Client and several separate queries in your app all request the data for the Gravity Form with an ID of `123`, Apollo Client would only fetch that data once, then would reuse that data to resolve all of the queries that requested it.

Likewise, if you want to query to get an individual GF entry, you would need to do this:
`const id = btoa('GravityFormsEntry:123')`

Also, FYI– this plugin is in active development and isn't ready for use in production environments just yet. It doesn't do authentication/permissions checks currently, for example, and the main features are still being built out.
