### ISSUE TITLE
Field errors not being returned for invalid field when using submitGravityFormsForm mutation

### ISSUE THREAD

**Issue by kellenmace** [harness-software/wp-graphql-gravity-forms#102]
## Bug Description

If I submit a form with one or more invalid field values using the `submitGravityFormsForm` mutation, no errors are returned to the client. A success response is sent back with an `entryId` set to `null`.

Plugin versions I'm using:

- Gravity Forms: 2.5.0.1
- WPGraphQL: 1.3.7
- WPGraphQL for Gravity Forms: 0.5.0

Screenshot:
<img width="796" alt="Screen Shot 2021-05-03 at 5 18 06 PM" src="https://user-images.githubusercontent.com/5306336/116935897-09a53c00-ac35-11eb-91ad-f65ebb599704.png">

## Expected Behavior

When a form is submitted with one or more invalid field values, a `UserError` should be thrown that includes data about the invalid field(s).

## Steps to Reproduce

Create a form with a single-line text field. Set its Max Length property to 5 characters and save the form.

In the GraphiQL instance embedded in the wp-admin, submit the form using a mutation like the one below. Note that the character count being passed in is invalid.

```graphql
mutation submitForm {
  submitGravityFormsForm(input: {
    formId: 1,
    fieldValues: [
      {
        id: 1,
        value: "123456789"
      },
    ]
  }) {
    entryId
  }
}
```

Confirm that no errors are returned, and that an `entryId` of `null` is in the response.

**Comment by justlevine** [comment]
To see field validation errors, you should be returning the `errors` field. 

```graphql
mutation submitForm {
  submitGravityFormsForm(input: {
    formId: 1,
    fieldValues: [
      {
        id: 1,
        value: "123456789"
      },
    ]
  }) {
    entryId
    errors {
      id
      message
    }
  }
}
```

This is from v0.5.0 + GF v2.5.0.1:
![image](https://user-images.githubusercontent.com/29322304/117017878-f9876e00-acc1-11eb-9e01-3849a2a079a1.png)

if the above mutation isnt working for you, let me know!

**Comment by kellenmace** [comment]
Ah, that's right. Thank you- I've got my frontend app working now.

This does have me wondering if throwing a new UserError would be more appropriate, though 🤔. 

If I'm using Apollo Client in my frontend app and fire off this mutation, errors could appear in two different places in the response:

1. If there was a network error, a UserError was thrown on the server, etc. then the error will be in the error variable that Apollo Client provides.
1. I have to drill down to `data.submitGravityFormsForm.errors` to determine if any field values were invalid.

Maybe using a `UserError` would be insufficient for passing along the data for _all_ errors, though (the id and message for each invalid value). Just thinking out loud at this point :)

I have my app working, so I'll close out this issue. Thanks again for the reminder about the `errors` field! 👍

**Comment by justlevine** [comment]
@kellenmace its a good discussion to have.

My current approach is loosely based on [this article from a few years ago](https://itnext.io/the-definitive-guide-to-handling-graphql-errors-e0c58b52b5e1). TL;DR if the error isnt caused by GraphQL, but is a valid response from Gravity Forms, then it should be returned as a `field` thats part of the response, not as thrown `UserError`.

With `submitGravityFormsForm`, the underlying `GFAPI::process_form()` function worked as expected, and returned the expected response (other fields passed server-side validation, these fields failed). If it was a draft entry, the entry would even be saved to the database.

Contrast that to trying to submit `fieldValues.checkboxValues` to a `TextField`. Or submitting any values to a form that doesnt exist. Or the aforementioned network error. Since those means the mutation itself didnt complete, a `UserError` is thrown.

All that said, I havn't revisited the topic in quite some time, so I'm open to more opinions :-)
