### ISSUE TITLE
Inconsistent types for choices field

### ISSUE THREAD

**Issue by TylerBarnes** [harness-software/wp-graphql-gravity-forms#12]
With this query:
```graphql
{
  gravityFormsForms {
    nodes {
      fields {
        nodes {
          __typename

          ... on ChainedSelectField {
            choices {
              text
            }
          }

          ... on CalculationField {
            choices
          }
        }
      }
    }
  }
}
```

I get this result:
```json
{
  "errors": [
    {
      "message": "Fields \"choices\" conflict because they return conflicting types [ChainedSelectChoiceProperty] and String. Use different aliases on the fields to fetch both if this was intentional.",
      "category": "graphql",
      "locations": [
        {
          "line": 9,
          "column": 13
        },
        {
          "line": 15,
          "column": 13
        }
      ]
    }
  ]
}
```

There seem to be these two conflicting types for this field across a few other inline fragment types as well, but I just added 2 here for reference.

**Comment by kellenmace** [comment]
@TylerBarnes Thanks for reporting this one too.

I simply removed the Calculation field from the project to address this issue. It does not conform to the patterns that the currently support fields do, namely it has a `type` of `product` that differs from the type of the input, which is actually `calculation`.

I don't think it's worth doing a significant refactor to support it right now, since no other product fields are supported; nobody is using the plugin for anything related to products at this point, so there's no real need for it. It could be added back in at a future date if and when support for other product fields is added to the project, and there's a need for it.
