### ISSUE TITLE
Conflict with WPGraphQL new version 1.6.2 and graphql IDE not working

### ISSUE THREAD

**Issue by shrenikTrukky** [harness-software/wp-graphql-gravity-forms#140]
WPGraphQL IDE not working with current wp-graphql-gravity-forms version. showing error in the 
<img width="1440" alt="Screenshot 2021-07-30 at 9 50 46 AM" src="https://user-images.githubusercontent.com/15668512/128286925-2714615f-7934-41eb-abb4-2b84f23c2fbb.png">
console panel.

**Comment by justlevine** [comment]
@shrenikTrukky can you please try again with one of WP's default themes, and share
1. Your WP and PHP version.
2. A list of all enabled plugins and what version they're running.
3. The full GraphQL response. (With dev panel open, go to the Network tab, refresh the WPGraphiQL page,  and copy the response for `index.php?graphql`

The error you're seeing is most likely because a GraphQL type is not being registered in a way compatible with WPGraphQL v1.6.x. Version 0.7.3 of our plugin includes the required changes, but several other popular plugins in the WPGraphQL ecosystem (e.g. Gutenberg, Woo) are yet to be updated.

Also if you're registering any custom graphql interfaces or union types in your code, you will need to update their config.

**Comment by shrenikTrukky** [comment]
> @shrenikTrukky can you please try again with one of WP's default themes, and share
> 
> 1. Your WP and PHP version.
> 2. A list of all enabled plugins and what version they're running.
> 3. The full GraphQL response. (With dev panel open, go to the Network tab, refresh the WPGraphiQL page,  and copy the response for `index.php?graphql`
> 
> The error you're seeing is most likely because a GraphQL type is not being registered in a way compatible with WPGraphQL v1.6.x. Version 0.7.3 of our plugin includes the required changes, but several other popular plugins in the WPGraphQL ecosystem (e.g. Gutenberg, Woo) are yet to be updated.
> 
> Also if you're registering any custom graphql interfaces or union types in your code, you will need to update their config.

I'm Using Gutenberg also but I deactivated all and tried only gravity form but still get the issue. so I'm checking again it

**Comment by shrenikTrukky** [comment]
@justlevine ,Yes are right. it's solved. it was conflict with my custom graphql code. thanks
