### ISSUE TITLE
Add support for Captcha validation

### ISSUE THREAD

**Issue by techieyann** [harness-software/wp-graphql-gravity-forms#141]
## Is your feature request related to a problem? Please describe.

I suggested in #33 to ignore captcha fields on the backend, turns out there is a [verification step](https://developers.google.com/recaptcha/docs/verify#api-request) that google suggests to fully protect against re-using the same captcha key.

## Describe the solution you'd like

We need to actually hit the required endpoint from the backend to properly support recaptcha fields. This means we need a mutation to pass the response keys from google to the backend, and then process it during the form verification step.

## Additional context

It's not 100% necessary, but it would allow a malicious actor to manually pass a captcha field and re-use the success keys for 2 minutes.

**Comment by justlevine** [comment]
Hey @techieyann,
Verifying the recaptcha response via Google is something everyone should be doing. My question is if this should be happening via a call from GF on the server after the submission is made vs verifying it on the frontend _before_ the form data is submitted to WordPress (e.g. in react pseudocode `<SubmitButton disabled={ ! captcha response?.success} />`)

What do you see as the pros/cons?

From my understanding, it's more performant to verify on the frontend since were preventing the mutation call and the server side validation of all the other GF fields (GF validates these one at a time in the order they're saved to the form, so usually the captcha verification happens towards the end of the lifecycle).

The only benefit I can think of is making the dx easier for frontend beginners so they don't need to figure out how to implement the call to Google. But idk if this type of user actually exists, considering they anyway have to implement the recaptcha component.

**Comment by techieyann** [comment]
One of the required params on the POST is the Recaptcha secret key, which would need to be shared with clients; that kills that option in my mind.

> GF validates these one at a time in the order they're saved to the form

Is there a way to pull the captcha to the front of the line?

**Comment by justlevine** [comment]
Thanks for clarifying!

There's no way to change the validation order of GF itself, but we could leave the built in validation disabled, but do our own recaptcha verification earlier on in the mutation's lifecycle before we submit it through GFAPI::submit_form().

**Comment by justlevine** [comment]
@techieyann I've been playing around with ways to make Captcha fields work natively - where the field value is simply the response for whatever supported Captcha service you're using. 

With a bit of extra work, we could even still supply a `verifyCaptcha` mutation that would preempt double-validation on submission while the reCaptcha response is still valid.

Either way this should solve the need of exposing the secret key to the frontend 🤞

**Comment by techieyann** [comment]
amazing, thank you for this @justlevine !
