### ISSUE TITLE
Plugin Activation breaks site. Parse error: syntax error, unexpected '=>'

### ISSUE THREAD

**Issue by valikwork** [harness-software/wp-graphql-gravity-forms#19]
HI everyone!
Every time i activate plugin it breaks site. with debbug on gives this: 'Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /www/wp-content/plugins/wp-graphql-gravity-forms-master/src/WPGraphQLGravityForms.php on line 180'
Can anyone assist with this.
Thanks!

P.s. WP version 5.4.2 | PHP version 7.3

**Comment by kellenmace** [comment]
Hi @valikwork. As stated in the readme, the minimum requirement for PHP is 7.4. You're getting that error because the plugin uses arrow functions, a.k.a. short closures that were introduced in PHP 7.4.

Can you please consider upgrading your project to PHP 7.4, if possible, then trying again? Thanks!
