### ISSUE TITLE
Unable to get Form Field Labels and Values

### ISSUE THREAD

**Issue by chrismathews2007** [harness-software/wp-graphql-gravity-forms#2]
Hi,

I installed a gravity form plugin. Getting the Form Name, Type Name. But unable to get field attributes. How to get field names ex:- (**First name, Last Name, Email, etc...**).

I read the documentation for future enhancements. how long time will be taken for this implementation?

Is there possible to post data with the type name? Please let me know If possible how to implement it.

`mutation {
  createGravityFormsEntry(input: {clientMutationId: "21", formId: 2}) {
    clientMutationId
    entry {
      form {
        node {
          id
          title
          fields {
            nodes {
              __typename
            }
          }
        }
      }
    }
  }
}`

**Comment by kellenmace** [comment]
Hi @chrismathews2007. You can use fragments in order to query for fields within a form. I just updated the readme for the project with a number of examples that should get you started: https://github.com/harness-software/wp-graphql-gravity-forms/blob/master/README.md

Yes, we do have form submission support, though not all field types are supported yet. We're still missing file upload field support, for instance – I'm working on that one this week. Enjoy! 👍🏼
