### ISSUE TITLE
Major bugs with Consent Field (Required not working and consentValue invalid)

### ISSUE THREAD

**Issue by TomDoFuture** [harness-software/wp-graphql-gravity-forms#322]
### Description

First off the docs tell you to use consentValue when submitting the form, doesnt work. You have to use value instead

Secondly, I set the field to required but I dont get an error when the box is left unchecked.

### Steps to reproduce

1. Submit a form, submit a GQL query on the Consent field. Make sure consent field is required
2. use the consentValue thingy from the documentation. 
3. Observe it being invalid because it is not defined on FormFieldsValueInput
4. Try value instead of consentValue, now it works, except you haven't checked the box yet, form submitted successfully?????

### Plugin Version

1.15

### Gravity Forms Version

2.36

### WordPress Version

6.02

### WPGraphQL Version

1.11.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @TomDoFuture 👋 and thanks for taking the time to report! I'm trying to replicate now.

Can you please confirm what version of `WPGraphQL for Gravity Forms` (it should be `v0.11.7`) and  `Gravity Forms` you're using (it needs to be _at least_ `v2.5.x`, but we recommend using the latest version of that as well )?

**Comment by TomDo1234** [comment]
@justlevine 

Hello Justle, this is my personal Github account, the OP is my work account.

I want to correct some details, my Gravity forms is 2.6.7,  WP Graphql for Gravity forms is now 0.11.7 as I just updated and tested again.

I also want to clarify that its not that "Its still being submitted when required consents are unchecked", but even when I do value as "false" it shows up on the backend as "Yes this is ticked"

**Comment by justlevine** [comment]
On further review, the issue seems to be with _the documentation_, which seems wasn't correctly updated in the v0.10 release.

The `consentValue` input was intentionally replaced with `value` in `v0.10.0`(https://github.com/harness-software/wp-graphql-gravity-forms/pull/196), in order to make it easier to use and bring it in line with how `[Gravity Forms behaves natively](https://github.com/wp-premium/gravityforms/blob/master/includes/fields/class-gf-field-consent.php#L263-279).

Any truthy string sent via `value` (GF native defaults to using the checkbox label) will mark the field value `true`, with an empty string or - better yet - leaving the field off the `fieldValues` mutation input array marking the field value `false`.

Here's an example for a consent field that one *is not* required to accept. 
![image](https://user-images.githubusercontent.com/29322304/197377047-c9552b86-e3cc-4f54-a7cc-0657f55a8fa2.png)

And when I change the field so it *is required*, it correctly returns an error message, as the user is required to consent.
![image](https://user-images.githubusercontent.com/29322304/197377097-7bd52923-ec19-4efe-b66f-84522b2f34b9.png)

I'll get to work fixing the docs ASAP - let me know if you have further thoughts and questions.

**Comment by justlevine** [comment]
Fixed via https://github.com/harness-software/wp-graphql-gravity-forms/commit/bf84420f3e61aabfb3ccb05ed8736eb2308d1c7f
